'use client';

import { ArrowLeft, ArrowRight, Check, ShieldCheck, TicketCheck } from 'lucide-react';
import type { JourneyIntent } from '@/types/journey';
import { berths, genders, type BookingDetails, type BookingFlow, type PassengerDetails } from '@/lib/chat/bookingFlow';
import { JourneyTimeline } from './JourneyTimeline';
import { TravelServices } from './TravelServices';

export function ChatBookingPanel({ flow, intent, busy, onChange, onReview, onBack }: { flow: BookingFlow; intent: JourneyIntent; busy: boolean; onChange: (details: BookingDetails) => void; onReview: () => void; onBack: () => void }) {
  const { journey, details, phase } = flow;
  const fee = details.passengers.length * 59;
  const total = journey.totalFare + fee;
  const amount = (value: number) => `₹${value.toLocaleString('en-IN')}`;
  const updatePassenger = (index: number, key: keyof PassengerDetails, value: string) => onChange({ ...details, passengers: details.passengers.map((passenger, position) => position === index ? { ...passenger, [key]: value } : passenger) });
  return <section className="chat-booking-panel" aria-label="Journey booking">
    {phase !== 'completed' ? <button className="back-link" type="button" onClick={onBack}><ArrowLeft size={15} /> Change journey</button> : null}
    <ol className="chat-booking-steps" aria-label="Booking progress">{['Travellers', 'Review', 'Summary'].map((label, index) => <li key={label} aria-current={index === (phase === 'collecting' ? 0 : phase === 'review' ? 1 : 2) ? 'step' : undefined}><span>{index < (phase === 'collecting' ? 0 : phase === 'review' ? 1 : 2) ? <Check size={13} /> : index + 1}</span>{label}</li>)}</ol>
    <div className="chat-booking-heading"><p className="section-label">{phase === 'completed' ? 'Journey summary' : 'Your selected journey'}</p><h2>{phase === 'completed' ? 'Your journey is ready.' : phase === 'review' ? 'One final check' : 'Who’s travelling?'}</h2><p>{phase === 'collecting' ? 'Share details in chat, or enter them here.' : phase === 'review' ? 'Check every detail before confirming in chat.' : `${intent.originCity} → ${intent.destinationCity}`}</p></div>
    <article className="chat-booking-journey"><header><div><h3>{journey.trainName}</h3><span>#{journey.trainNumber} · {journey.classOption.code} · {journey.classOption.name}</span></div><strong className={journey.classOption.status === 'CONFIRMED' ? 'status-confirmed' : 'status-warning'}>{journey.classOption.status === 'CONFIRMED' ? 'Confirmed seats' : `${journey.classOption.status === 'WAITLIST' ? 'WL' : 'RAC'} ${journey.classOption.position ?? ''}`}</strong></header><JourneyTimeline journey={journey} expanded /></article>
    {journey.classOption.status !== 'CONFIRMED' ? <p className="chat-booking-warning" role="note">{journey.classOption.status === 'WAITLIST' ? 'This journey is waitlisted. A seat is not confirmed.' : 'RAC does not guarantee a full berth.'} Confirm only if you accept this availability.</p> : null}
    {phase === 'collecting' ? <form className="chat-booking-form" onSubmit={(event) => { event.preventDefault(); onReview(); }}>
      {details.passengers.map((passenger, index) => <fieldset key={index}><legend>Traveller {index + 1}</legend><div className="chat-booking-fields"><label>Full name<input autoComplete={index === 0 ? 'name' : 'off'} value={passenger.name} maxLength={100} minLength={2} required onChange={(event) => updatePassenger(index, 'name', event.target.value)} /></label><label>Age<input type="number" min="1" max="120" step="1" value={passenger.age} required onChange={(event) => updatePassenger(index, 'age', event.target.value)} /></label><label>Gender<select required value={passenger.gender} onChange={(event) => updatePassenger(index, 'gender', event.target.value)}><option value="">Select</option>{genders.map((gender) => <option key={gender}>{gender}</option>)}</select></label><label>Berth preference<select value={passenger.berth} onChange={(event) => updatePassenger(index, 'berth', event.target.value)}>{berths.map((berth) => <option key={berth}>{berth}</option>)}</select></label></div></fieldset>)}
      <fieldset><legend>Booking contact</legend><div className="chat-booking-fields"><label>Email<input type="email" autoComplete="email" value={details.email} maxLength={254} required onChange={(event) => onChange({ ...details, email: event.target.value })} /></label><label>Mobile number<input type="tel" autoComplete="tel" value={details.phone} maxLength={30} required onChange={(event) => onChange({ ...details, phone: event.target.value })} /></label></div></fieldset>
      <p className="chat-booking-note"><ShieldCheck size={14} /> Details shared in chat are processed by Gemini. Never share payment credentials.</p>
      <button className="primary-button" type="submit" disabled={busy}>Review details <ArrowRight size={16} /></button>
    </form> : <section className="chat-booking-review" aria-label="Final booking details"><header><h3>Travellers & contact</h3>{phase === 'review' ? <button className="back-link" type="button" onClick={() => onChange(details)}>Edit details</button> : null}</header><ul>{details.passengers.map((passenger, index) => <li key={index}><strong>{passenger.name}</strong><span>{passenger.age} years · {passenger.gender} · {passenger.berth === 'No preference' ? 'Any berth' : `${passenger.berth} berth requested`}</span></li>)}</ul><div className="chat-booking-contact"><span>{details.email}</span><span>{details.phone}</span></div></section>}
    <section className="chat-booking-fare" aria-label="Fare summary"><div><span>{journey.roadLegs?.length ? 'Complete journey fare' : 'Train fare'} · {details.passengers.length} traveller{details.passengers.length === 1 ? '' : 's'}</span><strong>{amount(journey.totalFare)}</strong></div><div><span>Convenience fee</span><strong>{amount(fee)}</strong></div><div className="total"><span>Estimated total</span><strong>{amount(total)}</strong></div></section>
    {phase === 'review' ? <div className="chat-booking-confirm-note"><Check size={18} /><p>Ready? Reply <strong>“Confirm booking”</strong> in chat. You can change any detail first.</p></div> : null}
    {phase === 'completed' ? <><div className="chat-booking-reference"><TicketCheck size={24} /><div><span>Journey reference</span><strong>{flow.reference}</strong></div></div><TravelServices journey={journey} /></> : null}
    <p className="chat-booking-note">{phase === 'completed' ? 'Not a travel ticket. ' : ''}No payment is taken here. Complete ticketing and payment with the booking provider.</p>
  </section>;
}
